### ISSUE TITLE
Plugin doesn't work for assets under Webapp

### ISSUE THREAD

**Issue by alexflav23** [JetBrains/sbt-structure#21]
A common use case for our Scala projects running InteliJ IDEA 14 is projects with a webapp folder, usually under the api module. Without further ado, a lot of the files in webapp are generated by things like the `sbt-less` plugin or some JavaScript compiler.

To avoid having 5 versions of the same file on a `Cmd + Shift + N` and general ease of use, we mark these as excluded but the settings are absolutely never persisted. So the plugin is consistent at least, but unfortunately it is consistently wrong and completely disregarding any folders marked as `Excluded` from the interface.

Is there another way to use it or anything in particular we should do to make it work properly? E.g persist settings of excluded folders even with SBT auto-import?

**Comment by Alefas** [comment]
Please try https://github.com/JetBrains/sbt-ide-settings to exclude folders.
