### ISSUE TITLE
way to provide unmanaged sources / javadocs

### ISSUE THREAD

**Issue by fommil** [JetBrains/sbt-structure#31]
sorry, I thought I brought this to your attention before.

I am working on a big project where the sbt definition is generated and the jars are all explicitly listed (this doesn't speed up resolution as much as you'd think, see https://github.com/sbt/sbt/issues/2266 ) but this means that sources and javadocs are not visible in IntelliJ.

We've worked around this in ensime by providing some new keys, it would be good if you did something similar: https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala#L55

**Comment by dancingrobot84** [comment]
Thanks for the suggestion! I've moved it to the project that suits it a bit better.
