### ISSUE TITLE
sbt imports keep changing when refreshing

### ISSUE THREAD

**Issue by Steiny69** [JetBrains/sbt-structure#36]
We have a build where one sbt project depends on another. It seems any time that we change build.sbt and refresh the projects in IntelliJ then the `sbt.imports` attribute in the .iml file of the dependant project.

For example:
`<module ... sbt.import="..., $e96b7b71b866e93def03.util...>`
becomes:
`<module ... sbt.import="..., $e784dbeb1b84c8ac53df.util...>`

Is there anyway to prevent this? It gets really noisy when switching git branches a lot (we have the .iml files under source control).

**Comment by SonnevilleJ** [comment]
Having this issue with an SBT project in IntelliJ 2016.3.3 using the bundled SBT. I also have SBT 0.13.13 installed for command line use.

**Comment by jastice** [comment]
What is the reason for having the IDEA prject files under source control for sbt projects? Usually they are generated via sbt locally.

**Comment by SonnevilleJ** [comment]
@jastice, according to [this article](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) JetBrains recommends committing the IDEA project files to the repo.

**Comment by jastice** [comment]
For projects that are fully managed by IDEA, that's true.
For projects where the project structure is managed by an external tool such as sbt, it's generally better practice to not include it. You can gitignore the whole .idea directory, or just the xmls, /libraries and /modules of it if you want to share run configs, for instance.

I'm closing this issue, but if you have a usecase that requires including the project structure for sbt projects, please open an issue on https://youtrack.jetbrains.com/issues/SCL

**Comment by ngbinh** [comment]
Having to sbt refresh large projects in a large codebase with many engineers working on is very inefficient. Please consider fixing this or at least provide a work around.
