### ISSUE TITLE
Library dependencies keep getting reordered

### ISSUE THREAD

**Issue by Steiny69** [JetBrains/sbt-structure#37]
It seems that the order of the library dependencies in the .iml files is non-deterministic. When the build.sbt file changes and the projects are refreshed in IntelliJ then the `<orderEntry>` elements in the module .iml file get reordered. This creates a whole lot of merge conflicts between our git branches.

**Comment by jastice** [comment]
This *might* be fixed as a side-effect of some recent changes. If you like, try out the latest Nightly of the Scala plugin and see if it behaves more nicely: https://confluence.jetbrains.com/display/SCA/Scala+Plugin+Nightly

You can also consider not including the .iml in your repository for sbt projects, as it is generated anyway.
