### ISSUE TITLE
_JAVA_OPTIONS breaks Import SBT

### ISSUE THREAD

**Issue by ms-tg** [JetBrains/sbt-structure#4]
To reproduce:

  1.  Set \_JAVA\_OPTIONS

        export _JAVA_OPTIONS=-Xss3m -XX:MaxPermSize=256M

  2.  Launch IntelliJ

        /opt/IntelliJ/current/bin/idea.sh &

  3.  Attempt to Import an SBT project

        See failure with _JAVA_OPTIONS at top of log

To workaround this error, you can `unset _JAVA_OPTIONS` in the terminal from which you launch IntelliJ, after which Import SBT will work.

**Comment by ms-tg** [comment]
Hi, @dancingrobot84 do you know if this was fixed, or never reproduced, or what?

**Comment by dancingrobot84** [comment]
Hi @ms-tg! It was fixed long ago.

**Comment by ms-tg** [comment]
Ha, awesome :)
