### ISSUE TITLE
[error] (*/*:dumpStructure) java.io.IOException: The filename, directory name, or volume label syntax is incorrect 

### ISSUE THREAD

**Issue by OlegYch** [JetBrains/sbt-structure#44]
started happening on project import a few days ago
currently using sbt 0.13.12 and plugin 2016.2.671

**Comment by OlegYch** [comment]
on windows, with project containing relative ProjectRefs

**Comment by jastice** [comment]
Please track in YouTrack: [SCL-10642](https://youtrack.jetbrains.com/issue/SCL-10642)
If you can provide an example project, that would be helpful in reproducing the error.

**Comment by jastice** [comment]
Pushed a fix that should end  up in the next nightlies. Thanks for the report!
