### ISSUE TITLE
Please deploy to standard sbtplugins repo

### ISSUE THREAD

**Issue by LogicalTime** [JetBrains/sbt-structure#48]
It would be very convenient for you to publish the artifacts in the standard sbtplugins plugin repo as well:
I think it is here:
https://dl.bintray.com/sbt/sbt-plugin-releases/

**Comment by jastice** [comment]
What would this make easier for you? The plugin doesn't really have a use outside of IntelliJ, and it's not straightforward to add it to the sbt-plugin-releases repo right now with the way bintray works

**Comment by LogicalTime** [comment]
Companies & organizations that only proxy and mirror standard repos can't
get that SBT plugin easily.  Since so many people put their SBT plugins
there, I'm sure you guys could figure out a decent way to do it.

Btw, In case it sways you. I just bought the all intellij all products
license, and have used intellij idea for years. I think this is the first
request I have made. :-D

**Comment by jastice** [comment]
Gotcha, this is actually a major issue so I made a ticket for it:
https://youtrack.jetbrains.com/issue/SCL-11925

**Comment by LogicalTime** [comment]
Thank you. Much appreciated.

**Comment by jastice** [comment]
The plugins should be now also available via standard repo.

**Comment by LogicalTime** [comment]
Excellent. Thanks again.
