### ISSUE TITLE
error: value jetbrains is not a member of String

### ISSUE THREAD

**Issue by 123avi** [JetBrains/sbt-structure#52]
Hi ,
I am using intellij `Ultimate 2017.2` . I am  trying to open [this](https://github.com/sksamuel/elastic4s) sbt project but opening the build.sbt and selecting "open as project" I am keep getting : 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to elastic4s (in build file:/Users/xxx/Projects/elastic4s/)
<set>:1: error: value jetbrains is not a member of String
org.jetbrains.sbt.StructureKeys.sbtStructureOptions in Global := "download resolveClassifiers"
^
[error] Type error in expression
```

**Comment by jastice** [comment]
Thanks for the report. I created an issue for you on our issue tracker: https://youtrack.jetbrains.com/issue/SCL-12422
Please report any problems there.

Workaround for this: Disable the "use sbt shell for build and import" option.

**Comment by jastice** [comment]
The other workaround is renaming "org" in Build.autoImport to something else

**Comment by 123avi** [comment]
thanks @jastice can you please elaborate ?

**Comment by jastice** [comment]
the project has a `Build` AutoPlugin, which defines a value `org` in `autoImport`, which will shadow all the packages under `org` in sbt files, including the one we use to inject settings. Renaming it to something else should solve this problem.
